-- SQL Schema setup for Supabase (FMS database)
-- Copy and run this script inside your Supabase SQL Editor.

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- USERS Table
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  role text not null default 'OFFICER',
  "fullName" text,
  "allowedDivisions" text[] default '{}',
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- Seeding default admin user (username: admin, password: admin123)
insert into public.users (username, password, role, "fullName", "allowedDivisions")
values ('admin', 'admin123', 'ADMIN', 'System Administrator', '{"VISA", "EOID", "RESIDENCE", "ETD"}')
on conflict (username) do nothing;

-- Function to generate record tables
-- All record tables share a standard structure:
-- id, boxNumber, shelfNumber, cabinetNumber, fullName, sex, citizenship, passportNumber, requestNumber, date, serviceProvided, division, createdBy, attachments, createdAt, updatedAt

-- VISA Table
create table if not exists public.visa (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- EOID Table
create table if not exists public.eoid (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- EOID Normal Table
create table if not exists public.eoid_normal (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- EOID Underage Table
create table if not exists public.eoid_underage (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- RESIDENCE_ID Table
create table if not exists public.residence_id (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- ETD (Emergency Travel Document) Table
create table if not exists public.etd (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- ERITREAN_ID Table
create table if not exists public.eritrean_id (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- ALIEN_PASSPORT Table
create table if not exists public.alien_passport (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- YELLOW_CARD Table
create table if not exists public.yellow_card (
  id bigint generated by default as identity primary key,
  "boxNumber" text,
  "shelfNumber" text,
  "cabinetNumber" text,
  "fullName" text,
  "sex" text default 'MALE',
  "citizenship" text,
  "passportNumber" text,
  "requestNumber" text,
  "date" text,
  "serviceProvided" text,
  "createdBy" text,
  "attachments" jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);
