const { Pool } = require('pg');
const pool = new Pool({
  host: 'localhost',
  port: 5433,
  database: 'FileMgt',
  user: 'postgres',
  password: 'root'
});

async function checkSchema() {
  // Create table residence_id_cancellation
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.residence_id_cancellation (
        id               bigint generated by default as identity primary key,
        "personalId"     text,
        "boxNumber"      text,
        "shelfNumber"    text,
        "cabinetNumber"  text,
        "fullName"       text,
        sex              text default 'MALE',
        citizenship      text,
        "passportNumber" text,
        "requestNumber"  text,
        date             text,
        birthdate        text,
        "serviceProvided" text,
        "createdBy"      text,
        attachments      jsonb default '[]'::jsonb,
        "createdAt"      timestamp with time zone default now(),
        "updatedAt"      timestamp with time zone default now()
      );
    `);
    console.log('✅ Created residence_id_cancellation table successfully');
  } catch (err) {
    console.error('❌ Error creating table:', err.message);
  }

  const tables = ['visa', 'eoid', 'eoid_normal', 'eoid_underage', 'residence_id', 'etd', 'eritrean_id', 'alien_passport', 'residence_id_cancellation'];
  for (const t of tables) {
    const res = await pool.query(`
      SELECT column_name
      FROM information_schema.columns 
      WHERE table_name = $1;
    `, [t]);
    console.log(`\n--- Table: ${t} ---`);
    console.log(res.rows.map(r => r.column_name).join(', '));
  }
  await pool.end();
}

checkSchema();
