-- (Duplicate placeholder) Original schema moved into backend.
-- See pre-existing backend/file_magement_schema.sql for full contents.
-- SQL Schema setup for Supabase (FMS database)
-- Copy and run this script inside your Supabase SQL Editor.

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- USERS Table
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  role text not null default 'OFFICER',
  "fullName" text,
  "allowedDivisions" text[] default '{}',
  "createdAt" timestamp with time zone default timezone('utc'::text, now()),
  "updatedAt" timestamp with time zone default timezone('utc'::text, now())
);

-- Seeding default admin user (username: admin, password: admin123)
insert into public.users (username, password, role, "fullName", "allowedDivisions")
values ('admin', 'admin123', 'ADMIN', 'System Administrator', '{"VISA", "EOID", "RESIDENCE", "ETD"}')
on conflict (username) do nothing;

-- (truncated for brevity)
