const path = require('path');
const fs = require('fs');
const envPath = fs.existsSync(path.join(__dirname, '.env'))
  ? path.join(__dirname, '.env')
  : path.join(__dirname, '..', '.env');
require('dotenv').config({ path: envPath });
const express = require('express');
const cors = require('cors');
const { Pool } = require('pg');

const app = express();
const PORT = process.env.PORT || 3001;

// ─────────────────────────────────────────────────
//   DATABASE CONNECTION
// ─────────────────────────────────────────────────
const pool = new Pool({
  host:     process.env.DB_HOST     || 'localhost',
  port:     parseInt(process.env.DB_PORT) || 5432,
  database: process.env.DB_NAME     || 'FileMgt',
  user:     process.env.DB_USER     || 'postgres',
  password: process.env.DB_PASSWORD || 'root',
});

// Test connection on startup
pool.connect((err, client, release) => {
  if (err) {
    console.error('❌  Database connection FAILED:', err.message);
    console.error('    Check DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD in backend/.env');
  } else {
    console.log(`✅  Connected to PostgreSQL → ${process.env.DB_NAME}`);
    release();
    ensureMissingTables();
  }
});

// ─────────────────────────────────────────────────
//   AUTO-CREATE / MIGRATE TABLES & COLUMNS
// ─────────────────────────────────────────────────
async function ensureMissingTables() {
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.audit_logs (
        id          bigint generated by default as identity primary key,
        action      text,
        "storeName" text,
        "userId"    bigint,
        "userName"  text,
        "recordId"  bigint,
        "recordData"   jsonb,
        "previousData" jsonb,
        timestamp   timestamp with time zone default now(),
        "ipAddress" text
      );
    `);

    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.recycle_bin (
        id               bigint generated by default as identity primary key,
        "originalStore"  text,
        "recordData"     jsonb,
        "createdAt"      timestamp with time zone default now(),
        "updatedAt"      timestamp with time zone default now()
      );
    `);

    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.residence_id_cancellation (
        id               bigint generated by default as identity primary key,
        "personalId"     text,
        "boxNumber"      text,
        "shelfNumber"    text,
        "cabinetNumber"  text,
        "fullName"       text,
        sex              text default 'MALE',
        citizenship      text,
        "passportNumber" text,
        "requestNumber"  text,
        date             text,
        birthdate        text,
        "serviceProvided" text,
        "createdBy"      text,
        attachments      jsonb default '[]'::jsonb,
        "createdAt"      timestamp with time zone default now(),
        "updatedAt"      timestamp with time zone default now()
      );
    `);

    // Ensure guardian & metadata columns on EOID tables
    const eoidTables = ['eoid', 'eoid_underage', 'eoid_normal'];
    for (const tbl of eoidTables) {
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "guardianFullName" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "guardianPassportId" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "guardianRelationship" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "birthdate" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "eoidNumber" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "branch" text DEFAULT 'Head Office (Addis Ababa)';`).catch(() => {});
      // eoidType distinguishes EOID-NORMAL from EOID-UNDER-AGE in the unified eoid table
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "eoidType" text DEFAULT 'EOID-NORMAL';`).catch(() => {});
    }

    // Consolidate legacy EOID subtype tables into the unified eoid table.
    const legacyEoidTables = await pool.query(`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name IN ('eoid_normal', 'eoid_underage')
    `);
    if (legacyEoidTables.rows.some(row => row.table_name === 'eoid_normal')) await pool.query(`
      INSERT INTO public.eoid
        ("personalId", "boxNumber", "shelfNumber", "cabinetNumber", "fullName", sex,
         citizenship, "passportNumber", "requestNumber", date, birthdate, "serviceProvided",
         "eoidNumber", "eoidType", "branch", attachments, "createdBy", "createdAt", "updatedAt")
      SELECT "personalId", "boxNumber", "shelfNumber", "cabinetNumber", "fullName", sex,
             citizenship, "passportNumber", "requestNumber", date, birthdate, "serviceProvided",
             "eoidNumber", 'EOID-NORMAL', "branch", attachments, "createdBy", "createdAt", "updatedAt"
      FROM public.eoid_normal n
      WHERE NOT EXISTS (
        SELECT 1 FROM public.eoid e
        WHERE e."personalId" = n."personalId" AND e."eoidType" = 'EOID-NORMAL'
      );
    `).catch(() => {});
    if (legacyEoidTables.rows.some(row => row.table_name === 'eoid_underage')) await pool.query(`
      INSERT INTO public.eoid
        ("personalId", "boxNumber", "shelfNumber", "cabinetNumber", "fullName", sex,
         citizenship, "passportNumber", "requestNumber", date, birthdate, "serviceProvided",
         "eoidNumber", "eoidType", "branch", attachments, "createdBy", "createdAt", "updatedAt")
      SELECT "personalId", "boxNumber", "shelfNumber", "cabinetNumber", "fullName", sex,
             citizenship, "passportNumber", "requestNumber", date, birthdate, "serviceProvided",
             "eoidNumber", 'EOID-UNDER-AGE', "branch", attachments, "createdBy", "createdAt", "updatedAt"
      FROM public.eoid_underage u
      WHERE NOT EXISTS (
        SELECT 1 FROM public.eoid e
        WHERE e."personalId" = u."personalId" AND e."eoidType" = 'EOID-UNDER-AGE'
      );
    `).catch(() => {});

    // Ensure branch and physical archive location columns on all system file tables
    const allFileTables = ['visa', 'residence_id', 'residence_id_cancellation', 'etd', 'eritrean_id', 'alien_passport', 'eoid', 'eoid_underage', 'eoid_normal', 'workpermit'];
    const recordPrefixes = {
      visa: 'VSID',
      eoid: 'EOID',
      eoid_normal: 'EOID',
      eoid_underage: 'EOID',
      residence_id: 'RSID',
      residence_id_cancellation: 'RSCID',
      etd: 'ETDID',
      eritrean_id: 'ERID',
      alien_passport: 'APID',
      workpermit: 'WPID',
    };
    for (const tbl of allFileTables) {
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "firstName" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "middleName" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "lastName" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "recordNumber" text;`).catch(() => {});
      if (recordPrefixes[tbl]) {
        await pool.query(`UPDATE public."${tbl}" SET "recordNumber" = $1 || '-' || LPAD(id::text, 6, '0') WHERE "recordNumber" IS NULL`, [recordPrefixes[tbl]]).catch(() => {});
        await pool.query(`CREATE UNIQUE INDEX IF NOT EXISTS "${tbl}_recordNumber_key" ON public."${tbl}" ("recordNumber") WHERE "recordNumber" IS NOT NULL`).catch(() => {});
      }
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "branch" text DEFAULT 'Head Office (Addis Ababa)';`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "building" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "room" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "shelfNumber" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "boxNumber" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "folderNumber" text;`).catch(() => {});
      // OCR and attachment support
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "ocrText" text;`).catch(() => {});
      await pool.query(`ALTER TABLE public."${tbl}" ADD COLUMN IF NOT EXISTS "attachments" jsonb DEFAULT '[]'::jsonb;`).catch(() => {});
    }

    // Ensure user security, status, array columns
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "email" text;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "loginAttempts" integer DEFAULT 0;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "locked" boolean DEFAULT false;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "isActive" boolean DEFAULT true;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'active';`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "lastLogin" text;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "permissions" jsonb DEFAULT '{"add":true,"edit":true,"delete":true}'::jsonb;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "modulePermissions" jsonb DEFAULT '{}'::jsonb;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "branch" text DEFAULT 'Head Office (Addis Ababa)';`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "allowedBranches" jsonb DEFAULT '["Head Office (Addis Ababa)"]'::jsonb;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "allowedDocTypes" jsonb DEFAULT '[]'::jsonb;`).catch(() => {});
    await pool.query(`ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "allowedDivisions" jsonb DEFAULT '[]'::jsonb;`).catch(() => {});

    // Safe JSONB Column Migration for Array & Object fields
    const userJsonCols = ['allowedBranches', 'allowedDocTypes', 'allowedDivisions', 'permissions', 'modulePermissions'];
    for (const col of userJsonCols) {
      await pool.query(`
        ALTER TABLE public.users 
        ALTER COLUMN "${col}" TYPE jsonb 
        USING CASE 
          WHEN "${col}" IS NULL THEN '[]'::jsonb
          WHEN pg_typeof("${col}")::text = 'text[]' THEN to_jsonb("${col}")
          WHEN pg_typeof("${col}")::text = 'text' AND "${col}" LIKE '{%}' THEN to_jsonb(string_to_array(trim(both '{}' from "${col}"), ','))
          ELSE "${col}"::jsonb
        END;
      `).catch(() => {});
    }

    // Ensure branches table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.branches (
        id          bigint generated by default as identity primary key,
        code        text unique not null,
        name        text not null,
        city        text,
        address     text,
        "isActive"  boolean default true,
        "createdAt" timestamp with time zone default now(),
        "updatedAt" timestamp with time zone default now()
      );
    `);

    // Ensure updatedAt column exists on branches table if it was created previously
    await pool.query(`ALTER TABLE public.branches ADD COLUMN IF NOT EXISTS "updatedAt" timestamp with time zone default now();`).catch(() => {});

    // Seed default branches if empty
    const branchCheck = await pool.query('SELECT count(*) FROM public.branches').catch(() => ({ rows: [{ count: '0' }] }));
    if (branchCheck?.rows?.[0]?.count === '0') {
      const defaultBranches = [
        { code: 'HQ', name: 'Head Office (Addis Ababa)', city: 'Addis Ababa' },
        { code: 'AA-MAIN', name: 'Addis Ababa Main Branch', city: 'Addis Ababa' },
        { code: 'BOLE', name: 'Bole International Airport Branch', city: 'Addis Ababa' },
        { code: 'DD', name: 'Dire Dawa Branch', city: 'Dire Dawa' },
        { code: 'HAW', name: 'Hawassa Branch', city: 'Hawassa' },
        { code: 'BD', name: 'Bahir Dar Branch', city: 'Bahir Dar' },
        { code: 'MEK', name: 'Mekelle Branch', city: 'Mekelle' },
        { code: 'ADA', name: 'Adama Branch', city: 'Adama' },
        { code: 'JIM', name: 'Jimma Branch', city: 'Jimma' },
        { code: 'GON', name: 'Gondar Branch', city: 'Gondar' },
        { code: 'JIG', name: 'Jigjiga Branch', city: 'Jigjiga' },
        { code: 'SEM', name: 'Semera Branch', city: 'Semera' },
        { code: 'ASO', name: 'Assosa Branch', city: 'Assosa' },
        { code: 'GAM', name: 'Gambella Branch', city: 'Gambella' }
      ];
      for (const b of defaultBranches) {
        await pool.query(
          'INSERT INTO public.branches (code, name, city) VALUES ($1, $2, $3) ON CONFLICT (code) DO NOTHING',
          [b.code, b.name, b.city]
        ).catch(() => {});
      }
    }

    // Ensure custom modules table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS public.custom_modules (
        id               bigint generated by default as identity primary key,
        key              text unique not null,
        title            text not null,
        description      text,
        icon             text default 'FileText',
        color            text default '#10b981',
        prefix           text default 'MOD',
        "docTypes"       jsonb default '[]'::jsonb,
        "types"          jsonb default '[]'::jsonb,
        "customFields"   jsonb default '[]'::jsonb,
        "isActive"       boolean default true,
        "isSystem"       boolean default false,
        "createdAt"      timestamp with time zone default now(),
        "updatedAt"      timestamp with time zone default now()
      );
    `);

    // Whitelist all custom module tables from database
    const customMods = await pool.query('SELECT key FROM public.custom_modules').catch(() => ({ rows: [] }));
    if (customMods && customMods.rows) {
      customMods.rows.forEach(r => {
        if (r.key) {
          ALLOWED_TABLES.add(r.key);
          ALLOWED_TABLES.add(r.key.replace(/-/g, '_'));
        }
      });
    }

    // Ensure the default admin account exists for login compatibility.
    const adminCheck = await pool.query(`
      SELECT id FROM public.users
      WHERE username = 'admin' OR email = 'admin@ics.gov' OR email = 'admin@gmail.com'
      LIMIT 1;
    `).catch(() => ({ rows: [] }));

    if (!adminCheck.rows.length) {
      await pool.query(`
        INSERT INTO public.users (
          username, password, role, "fullName",
          "allowedDivisions", "permissions", "status",
          "isActive", "loginAttempts", "locked",
          "createdAt", "updatedAt"
        )
        VALUES (
          'admin', 'admin123', 'ADMIN', 'System Administrator',
          ARRAY['VISA', 'EOID', 'RESIDENCE', 'ETD']::text[],
          '{"add":true,"edit":true,"delete":true}'::jsonb,
          'active', true, 0, false,
          NOW(), NOW()
        )
        ON CONFLICT (username) DO NOTHING;
      `).catch(() => {});
    }

    console.log('✅  Tables audit_logs, recycle_bin, branches, custom_modules, and columns are ready.');
  } catch (err) {
    console.error('❌  Failed to ensure missing tables:', err.message);
  }
}

// ─────────────────────────────────────────────────
//   MIDDLEWARE
// ─────────────────────────────────────────────────
app.use(cors());
app.use(express.json({ limit: '50mb' }));

// Serve the built React app (used in production / LAN deployment)
const rootDistPath = path.join(__dirname, '..', 'dist');
const frontendDistPath = path.join(__dirname, '..', 'frontend', 'dist');
app.use(express.static(rootDistPath));
app.use(express.static(frontendDistPath));

// ─────────────────────────────────────────────────
//   SECURITY: WHITELIST ALLOWED TABLES
// ─────────────────────────────────────────────────
const ALLOWED_TABLES = new Set([
  'visa', 'eoid', 'eoid_normal', 'eoid_underage', 'residence_id',
  'etd', 'eritrean_id', 'alien_passport', 'residence_id_cancellation',
  'users', 'audit_logs', 'recycle_bin', 'custom_modules', 'branches'
]);

function tableOk(table, res) {
  if (!table) {
    if (res) res.status(400).json({ error: 'Table name is required' });
    return false;
  }
  const clean = table.toLowerCase();
  const norm = clean.replace(/-/g, '_');
  if (ALLOWED_TABLES.has(table) || ALLOWED_TABLES.has(clean) || ALLOWED_TABLES.has(norm)) {
    return true;
  }
  if (/^[a-z0-9_]+$/.test(norm)) {
    ALLOWED_TABLES.add(table);
    ALLOWED_TABLES.add(clean);
    ALLOWED_TABLES.add(norm);
    return true;
  }
  if (res) res.status(400).json({ error: `Unknown table: ${table}` });
  return false;
}

// Helper to create table for a custom module
async function createCustomModuleTable(key, customFields = []) {
  const tblName = key.replace(/-/g, '_');
  await pool.query(`
    CREATE TABLE IF NOT EXISTS public."${tblName}" (
      id               bigint generated by default as identity primary key,
      "recordNumber"   text unique,
      "personalId"     text,
      "boxNumber"      text,
      "shelfNumber"    text,
      "cabinetNumber"  text,
      "fullName"       text,
      "firstName"      text,
      "middleName"     text,
      "lastName"       text,
      sex              text default 'MALE',
      citizenship      text,
      "passportNumber" text,
      "requestNumber"  text,
      date             text,
      birthdate        text,
      "serviceProvided" text,
      "type"           text,
      "branch"         text default 'Head Office (Addis Ababa)',
      "customData"     jsonb default '{}'::jsonb,
      "createdBy"      text,
      attachments      jsonb default '[]'::jsonb,
      "createdAt"      timestamp with time zone default now(),
      "updatedAt"      timestamp with time zone default now()
    );
  `);
  ALLOWED_TABLES.add(tblName);
  ALLOWED_TABLES.add(key);
}

// Universal Parameter Cast Helper
function getParamPlaceholder(colName, index) {
  const jsonCols = [
    'permissions', 'attachments', 'recordData', 'previousData', 
    'customData', 'docTypes', 'types', 'customFields',
    'allowedBranches', 'allowedDocTypes', 'allowedDivisions'
  ];
  
  if (jsonCols.includes(colName)) {
    return `CASE WHEN $${index}::text IS NULL THEN '[]'::jsonb ELSE ($${index})::jsonb END`;
  }
  return `$${index}`;
}

function getRecordPrefix(table) {
  return {
    visa: 'VSID',
    eoid: 'EOID',
    eoid_normal: 'EOID',
    eoid_underage: 'EOID',
    residence_id: 'RSID',
    residence_id_cancellation: 'RSCID',
    etd: 'ETDID',
    eritrean_id: 'ERID',
    alien_passport: 'APID',
    workpermit: 'WPID',
  }[table] || null;
}

async function assignRecordNumber(client, table, id, requestedNumber) {
  if (requestedNumber || !id) return;
  const prefix = getRecordPrefix(table);
  if (!prefix) return;
  await client.query(
    `UPDATE public."${table}" SET "recordNumber" = $1 || '-' || LPAD($2::text, 6, '0') WHERE id = $2`,
    [prefix, id]
  );
}

async function ensureRecordColumns(client, table) {
  const columns = {
    personalId: 'text',
    boxNumber: 'text',
    shelfNumber: 'text',
    cabinetNumber: 'text',
    folderNumber: 'text',
    fullName: 'text',
    firstName: 'text',
    middleName: 'text',
    lastName: 'text',
    sex: 'text',
    citizenship: 'text',
    passportNumber: 'text',
    requestNumber: 'text',
    date: 'text',
    birthdate: 'text',
    serviceProvided: 'text',
    branch: 'text',
    building: 'text',
    room: 'text',
    recordNumber: 'text',
    attachmentStatus: 'text',
    createdBy: 'text',
    createdAt: 'timestamp with time zone',
    updatedAt: 'timestamp with time zone',
    ocrText: 'text',
    attachments: "jsonb DEFAULT '[]'::jsonb",
  };
  const moduleColumns = {
    eoidNumber: 'text', eoidType: "text DEFAULT 'EOID-NORMAL'",
    guardianFullName: 'text', guardianPassportId: 'text', guardianRelationship: 'text',
    residenceIdNumber: 'text', residenceIdType: 'text', permanentId: 'text', temporaryId: 'text',
    companyName: 'text', etdNumber: 'text', etdType: 'text', eritreanIdNumber: 'text',
    alienPassportNumber: 'text', visaNumber: 'text', visaType: 'text', type: 'text',
  };
  for (const [column, definition] of Object.entries({ ...columns, ...moduleColumns })) {
    await client.query(`ALTER TABLE public."${table}" ADD COLUMN IF NOT EXISTS "${column}" ${definition};`);
  }
}

// Serializes values appropriately for PG Driver
function processValues(values) {
  return values.map(v => {
    if (v === null || v === undefined) {
      return null;
    }
    if (typeof v === 'object') {
      return JSON.stringify(v);
    }
    return v;
  });
}

// ─────────────────────────────────────────────────
//   SPECIAL ROUTES
// ─────────────────────────────────────────────────

// GET all custom system modules
app.get('/api/system-modules', async (req, res) => {
  try {
    const result = await pool.query('SELECT * FROM public.custom_modules ORDER BY id ASC');
    res.json(result.rows);
  } catch (err) {
    console.error('GET /api/system-modules error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// POST create a new custom system module
app.post('/api/system-modules', async (req, res) => {
  const { key, title, description, icon, color, prefix, docTypes, types, customFields, isActive } = req.body;
  if (!key || !title) {
    return res.status(400).json({ error: 'Module Key and Title are required' });
  }

  const cleanKey = key.trim().toLowerCase().replace(/[^a-z0-9_-]/g, '-');

  try {
    await createCustomModuleTable(cleanKey, customFields);

    const result = await pool.query(
      `INSERT INTO public.custom_modules 
        (key, title, description, icon, color, prefix, "docTypes", "types", "customFields", "isActive", "createdAt", "updatedAt")
       VALUES ($1, $2, $3, $4, $5, $6, ($7)::jsonb, ($8)::jsonb, ($9)::jsonb, $10, NOW(), NOW())
       ON CONFLICT (key) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        icon = EXCLUDED.icon,
        color = EXCLUDED.color,
        prefix = EXCLUDED.prefix,
        "docTypes" = EXCLUDED."docTypes",
        "types" = EXCLUDED."types",
        "customFields" = EXCLUDED."customFields",
        "isActive" = EXCLUDED."isActive",
        "updatedAt" = NOW()
       RETURNING *`,
      [
        cleanKey,
        title,
        description || '',
        icon || 'FileText',
        color || '#10b981',
        prefix || cleanKey.substring(0, 3).toUpperCase(),
        JSON.stringify(docTypes || []),
        JSON.stringify(types || []),
        JSON.stringify(customFields || []),
        isActive !== undefined ? isActive : true
      ]
    );

    res.status(201).json(result.rows[0]);
  } catch (err) {
    console.error('POST /api/system-modules error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// PUT update a custom system module
app.put('/api/system-modules/:id', async (req, res) => {
  const { id } = req.params;
  const { title, description, icon, color, prefix, docTypes, types, customFields, isActive } = req.body;

  try {
    const result = await pool.query(
      `UPDATE public.custom_modules SET
        title = COALESCE($1, title),
        description = COALESCE($2, description),
        icon = COALESCE($3, icon),
        color = COALESCE($4, color),
        prefix = COALESCE($5, prefix),
        "docTypes" = COALESCE(($6)::jsonb, "docTypes"),
        "types" = COALESCE(($7)::jsonb, "types"),
        "customFields" = COALESCE(($8)::jsonb, "customFields"),
        "isActive" = COALESCE($9, "isActive"),
        "updatedAt" = NOW()
       WHERE id = $10
       RETURNING *`,
      [
        title,
        description,
        icon,
        color,
        prefix,
        docTypes ? JSON.stringify(docTypes) : null,
        types ? JSON.stringify(types) : null,
        customFields ? JSON.stringify(customFields) : null,
        isActive,
        id
      ]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Module not found' });
    }

    res.json(result.rows[0]);
  } catch (err) {
    console.error('PUT /api/system-modules error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// DELETE a custom system module
app.delete('/api/system-modules/:id', async (req, res) => {
  const { id } = req.params;
  try {
    await pool.query('DELETE FROM public.custom_modules WHERE id = $1', [id]);
    res.json({ success: true });
  } catch (err) {
    console.error('DELETE /api/system-modules error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// DELETE old audit logs older than N days
app.delete('/api/audit_logs/old', async (req, res) => {
  const daysToKeep = parseInt(req.query.daysToKeep) || 90;
  try {
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - daysToKeep);
    await pool.query('DELETE FROM public.audit_logs WHERE timestamp < $1', [cutoff.toISOString()]);
    res.json({ success: true });
  } catch (err) {
    console.error('DELETE audit_logs/old error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// DELETE all records from recycle_bin (empty bin)
app.delete('/api/recycle_bin/all', async (req, res) => {
  try {
    await pool.query('DELETE FROM public.recycle_bin');
    res.json({ success: true });
  } catch (err) {
    console.error('DELETE recycle_bin/all error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// POST bulk import records
app.post('/api/:table/bulk', async (req, res) => {
  const { table } = req.params;
  if (!tableOk(table, res)) return;

  const { records } = req.body;
  if (!Array.isArray(records) || records.length === 0) {
    return res.status(400).json({ error: 'No records provided' });
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await ensureRecordColumns(client, table);

    for (const record of records) {
      const data = { ...record };
      delete data.id;
      if (!data.createdAt) data.createdAt = new Date().toISOString();
      if (!data.updatedAt) data.updatedAt = new Date().toISOString();
      if (!data.attachments) data.attachments = [];

      const cols   = Object.keys(data);
      const vals   = processValues(Object.values(data));
      const quoted = cols.map(c => `"${c}"`).join(', ');
      const ph     = cols.map((c, i) => getParamPlaceholder(c, i + 1)).join(', ');

      const inserted = await client.query(
        `INSERT INTO public."${table}" (${quoted}) VALUES (${ph}) RETURNING id, "recordNumber"`,
        vals
      );
      await assignRecordNumber(client, table, inserted.rows[0]?.id, inserted.rows[0]?.recordNumber);
    }

    await client.query('COMMIT');
    res.json({ success: true });
  } catch (err) {
    await client.query('ROLLBACK');
    console.error(`POST /${table}/bulk error:`, err.message);
    res.status(500).json({ error: err.message });
  } finally {
    client.release();
  }
});

// ─────────────────────────────────────────────────
//   HEALTH CHECK
// ─────────────────────────────────────────────────
app.get('/api/health', async (req, res) => {
  try {
    await pool.query('SELECT 1');
    res.json({ status: 'ok', database: process.env.DB_NAME });
  } catch (err) {
    res.status(500).json({ status: 'error', message: err.message });
  }
});

// ─────────────────────────────────────────────────
//   GENERIC CRUD ROUTES
// ─────────────────────────────────────────────────

// GET all records
app.get('/api/:table', async (req, res) => {
  const { table } = req.params;
  if (!tableOk(table, res)) return;
  const targetTable = table.replace(/-/g, '_');

  try {
    let query, params = [];

    if (targetTable === 'audit_logs') {
      const conditions = [];
      const { action, storeName, userId, startDate, endDate } = req.query;

      if (action)    { params.push(action);     conditions.push(`action = $${params.length}`); }
      if (storeName) { params.push(storeName);  conditions.push(`"storeName" = $${params.length}`); }
      if (userId)    { params.push(userId);     conditions.push(`"userId" = $${params.length}`); }
      if (startDate) { params.push(startDate);  conditions.push(`timestamp >= $${params.length}`); }
      if (endDate) {
        const end = endDate.includes('T') ? endDate : `${endDate}T23:59:59.999Z`;
        params.push(end);
        conditions.push(`timestamp <= $${params.length}`);
      }

      const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
      query = `SELECT * FROM public.audit_logs ${where} ORDER BY timestamp DESC`;
    } else {
      query = `SELECT * FROM public."${targetTable}" ORDER BY id DESC`;
    }

    const result = await pool.query(query, params);
    res.json(result.rows);
  } catch (err) {
    console.error(`GET /${table} error:`, err.message);
    res.status(500).json({ error: err.message });
  }
});

// POST add a single record
app.post('/api/:table', async (req, res) => {
  const { table } = req.params;
  if (!tableOk(table, res)) return;
  const targetTable = table.replace(/-/g, '_');

  const data = req.body;
  if (!data || Object.keys(data).length === 0) {
    return res.status(400).json({ error: 'No data provided' });
  }

  try {
    await ensureRecordColumns(pool, targetTable);
    const cols   = Object.keys(data);
    const vals   = processValues(Object.values(data));
    const quoted = cols.map(c => `"${c}"`).join(', ');
    const ph     = cols.map((c, i) => getParamPlaceholder(c, i + 1)).join(', ');

    const result = await pool.query(
      `INSERT INTO public."${targetTable}" (${quoted}) VALUES (${ph}) RETURNING *`,
      vals
    );
    await assignRecordNumber(pool, targetTable, result.rows[0]?.id, result.rows[0]?.recordNumber);
    if (result.rows[0]?.id && !result.rows[0]?.recordNumber) {
      result.rows[0].recordNumber = `${getRecordPrefix(targetTable)}-${String(result.rows[0].id).padStart(6, '0')}`;
    }
    res.json(result.rows[0]);
  } catch (err) {
    console.error(`POST /${table} error:`, err.message);
    res.status(500).json({ error: err.message });
  }
});

// PUT update a record by ID
app.put('/api/:table/:id', async (req, res) => {
  const { table, id } = req.params;
  if (!tableOk(table, res)) return;
  const targetTable = table.replace(/-/g, '_');

  let data = { ...req.body };
  delete data.id;

  if (Object.keys(data).length === 0) {
    return res.status(400).json({ error: 'No data provided' });
  }

  try {
    // Skip updatedAt if it's not present in the request body
    // (The database may not have this column yet)
    if (!data.updatedAt && Object.keys(data).includes('isActive')) {
      // Only branches table uses isActive, and we want to avoid updatedAt errors
      // so don't add it if it's not already in the request
    }

    const cols = Object.keys(data);
    const vals = processValues(Object.values(data));
    const set  = cols.map((c, i) => `"${c}" = ${getParamPlaceholder(c, i + 1)}`).join(', ');

    vals.push(id);
    const result = await pool.query(
      `UPDATE public."${targetTable}" SET ${set} WHERE id = $${vals.length} RETURNING *`,
      vals
    );
    res.json(result.rows[0] || { success: true });
  } catch (err) {
    console.error(`PUT /${table}/${id} error:`, err.message);
    res.status(500).json({ error: err.message });
  }
});

// DELETE a record by ID
app.delete('/api/:table/:id', async (req, res) => {
  const { table, id } = req.params;
  if (!tableOk(table, res)) return;
  const targetTable = table.replace(/-/g, '_');

  try {
    await pool.query(`DELETE FROM public."${targetTable}" WHERE id = $1`, [id]);
    res.json({ success: true });
  } catch (err) {
    console.error(`DELETE /${table}/${id} error:`, err.message);
    res.status(500).json({ error: err.message });
  }
});

// ─────────────────────────────────────────────────
//   SPA FALLBACK
// ─────────────────────────────────────────────────
app.get('*', (req, res) => {
  const indexPath = fs.existsSync(path.join(frontendDistPath, 'index.html'))
    ? path.join(frontendDistPath, 'index.html')
    : path.join(rootDistPath, 'index.html');
  if (fs.existsSync(indexPath)) {
    res.sendFile(indexPath);
  } else {
    res.status(404).send('Frontend build not found. Please run npm run build.');
  }
});

// ─────────────────────────────────────────────────
//   START SERVER
// ─────────────────────────────────────────────────
app.listen(PORT, '0.0.0.0', () => {
  console.log('');
  console.log(`🚀  FMS Server is running!`);
  console.log(`    Local:   http://localhost:${PORT}`);
  console.log(`    Network: http://<your-server-ip>:${PORT}`);
  console.log('');
});